.TH "SpriteContoller Directory Reference" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteContoller Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSpriteController\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSpriteController\&.hpp\fP"
.br
.in -1c
