.TH "Utils/debug.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils/debug.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "sf::RectangleShape \fBdebugRectangle\fP (sf::FloatRect rect)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "sf::RectangleShape debugRectangle (sf::FloatRect rect)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
