.TH "Enemies/EyeEnemy.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enemies/EyeEnemy.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Audio\&.hpp>\fP
.br
\fC#include '\&.\&./GameObject/GameObject\&.hpp'\fP
.br
\fC#include 'cmath'\fP
.br
\fC#include <\&.\&./external/PriorityQueue/PriorityQueue\&.hpp>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEyeEnemy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
