.TH "Game/Game.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game/Game.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Audio\&.hpp>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./Bullet/Bullet\&.hpp'\fP
.br
\fC#include '\&.\&./Enemies/EyeEnemy\&.hpp'\fP
.br
\fC#include '\&.\&./GameObject/GameObject\&.hpp'\fP
.br
\fC#include '\&.\&./Player/Player\&.hpp'\fP
.br
\fC#include '\&.\&./SettingsManager/SettingsManager\&.hpp'\fP
.br
\fC#include '\&.\&./SpriteContoller/SpriteController\&.hpp'\fP
.br
\fC#include '\&.\&./TileMap/TileMap\&.hpp'\fP
.br
\fC#include '\&.\&./external/SimplexNoise/SimplexNoise\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
