.TH "Game" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Game\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGame\fP (unsigned int h=600U, unsigned int w=800U)"
.br
.RI "создать объект Игры, с окном с указанными размерами "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "запустить игру "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game::Game (unsigned int h = \fC600U\fP, unsigned int w = \fC800U\fP)"

.PP
создать объект Игры, с окном с указанными размерами 
.PP
\fBParameters\fP
.RS 4
\fIh\fP высота окна 
.br
\fIw\fP ширина окна 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Game::run ()"

.PP
запустить игру 

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
