.TH "external/toml/literal.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
external/toml/literal.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'parser\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtoml\fP"
.br
.ti -1c
.RI "namespace \fBtoml::literals\fP"
.br
.ti -1c
.RI "namespace \fBtoml::literals::toml_literals\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "inline \fB::toml::basic_value\fP< \fBTOML11_DEFAULT_COMMENT_STRATEGY\fP, std::unordered_map, std::vector > \fBtoml::literals::toml_literals::literal_internal_impl\fP (\fB::toml::detail::location\fP loc)"
.br
.ti -1c
.RI "inline \fB::toml::basic_value\fP< \fBTOML11_DEFAULT_COMMENT_STRATEGY\fP, std::unordered_map, std::vector > \fBtoml::literals::toml_literals::operator''_toml\fP (const char *str, std::size_t len)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
