.TH "PriorityQueue< T >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PriorityQueue< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PriorityQueue\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPriorityQueue\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBenqueue\fP (T item, int priority)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "T \fBdequeue\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBPriorityQueue\fP< T >\fB::PriorityQueue\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBPriorityQueue\fP< T >::dequeue ()\fC [inline]\fP"

.SS "template<class T > bool \fBPriorityQueue\fP< T >::empty () const\fC [inline]\fP"

.SS "template<class T > void \fBPriorityQueue\fP< T >::enqueue (T item, int priority)\fC [inline]\fP"

.SS "template<class T > int \fBPriorityQueue\fP< T >::size ()\fC [inline]\fP"

.SS "template<class T > size_t \fBPriorityQueue\fP< T >::size () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
