.TH "external/toml/region.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
external/toml/region.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include 'color\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtoml::detail::region_base\fP"
.br
.ti -1c
.RI "struct \fBtoml::detail::location\fP"
.br
.ti -1c
.RI "struct \fBtoml::detail::region\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtoml\fP"
.br
.ti -1c
.RI "namespace \fBtoml::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Iterator > std::string \fBtoml::detail::make_string\fP (Iterator first, Iterator last)"
.br
.ti -1c
.RI "std::string \fBtoml::detail::make_string\fP (std::size_t len, char c)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
