.TH "SettingsManager/SettingsManager.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingsManager/SettingsManager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include '\&.\&./external/toml\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSettingsManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
