.TH "SpriteContoller/SpriteController.cpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteContoller/SpriteController.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SpriteController\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
