.TH "SpriteContoller/SpriteController.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteContoller/SpriteController.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include '\&.\&./SettingsManager/SettingsManager\&.hpp'\fP
.br
\fC#include '\&.\&./TileMap/TileMap\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSpriteController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
