.TH "external/toml.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
external/toml.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'toml/parser\&.hpp'\fP
.br
\fC#include 'toml/literal\&.hpp'\fP
.br
\fC#include 'toml/serializer\&.hpp'\fP
.br
\fC#include 'toml/get\&.hpp'\fP
.br
\fC#include 'toml/macros\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOML11_VERSION_MAJOR\fP   3"
.br
.ti -1c
.RI "#define \fBTOML11_VERSION_MINOR\fP   7"
.br
.ti -1c
.RI "#define \fBTOML11_VERSION_PATCH\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TOML11_VERSION_MAJOR   3"

.SS "#define TOML11_VERSION_MINOR   7"

.SS "#define TOML11_VERSION_PATCH   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
