.TH "toml::detail::last_one_in_pack< T, Ts >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::last_one_in_pack< T, Ts >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utility\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = typename \fBlast_one_in_pack\fP< Ts\&.\&.\&. >::type"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T , typename \&.\&.\&. Ts> using \fBtoml::detail::last_one_in_pack\fP< T, Ts >::type =  typename \fBlast_one_in_pack\fP<Ts\&.\&.\&.>::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
