.TH "toml::detail::has_iterator< T >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::has_iterator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits decltypehas_iterator_impl::check< T >nullptr\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct toml::detail::has_iterator< T >"Intel C++ compiler can not use decltype in parent class declaration, here is a hack to work around it\&. https://stackoverflow.com/a/23953090/4692076 

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
