.TH "toml::detail::has_from_toml_method_impl" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::has_from_toml_method_impl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename C , template< typename \&.\&.\&. > class Tb, template< typename \&.\&.\&. > class A> static std::true_type \fBcheck\fP (decltype(std::declval< T >()\&.from_toml(std::declval<\fB::toml::basic_value\fP< C, Tb, A > >())) *)"
.br
.ti -1c
.RI "template<typename T , typename C , template< typename \&.\&.\&. > class Tb, template< typename \&.\&.\&. > class A> static std::false_type \fBcheck\fP (\&.\&.\&.)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename C , template< typename \&.\&.\&. > class Tb, template< typename \&.\&.\&. > class A> static std::false_type toml::detail::has_from_toml_method_impl::check ( \&.\&.\&.)\fC [static]\fP"

.SS "template<typename T , typename C , template< typename \&.\&.\&. > class Tb, template< typename \&.\&.\&. > class A> static std::true_type toml::detail::has_from_toml_method_impl::check (decltype(std::declval< T >()\&.from_toml(std::declval<\fB::toml::basic_value\fP< C, Tb, A > >())) *)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
