.TH "toml::detail::has_mapped_type< T >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::has_mapped_type< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits decltypehas_mapped_type_impl::check< T >nullptr\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
