.TH "toml::detail::has_from_toml_method< T, C, Tb, A >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::has_from_toml_method< T, C, Tb, A >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits decltypehas_from_toml_method_impl::check< T, C, Tb, A >nullptr\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
