.TH "toml::detail::is_std_tuple< T >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::is_std_tuple< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits std::false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
