.TH "toml::detail::conjunction<... >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::conjunction<... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits std::true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
