.TH "toml::color_ansi" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::color_ansi
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdetail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBcolorize\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBnocolorize\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBreset\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBbold\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBgrey\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBred\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBgreen\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fByellow\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBblue\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBmagenta\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBcyan\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBwhite\fP (std::ostream &os)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream & toml::color_ansi::blue (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::bold (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::colorize (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::cyan (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::green (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::grey (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::magenta (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::nocolorize (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::red (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::reset (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::white (std::ostream & os)\fC [inline]\fP"

.SS "std::ostream & toml::color_ansi::yellow (std::ostream & os)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
