.TH "toml::detail::either< Head, Tail... >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::either< Head, Tail... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <combinator\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBresult\fP< \fBregion\fP, \fBnone_t\fP > \fBinvoke\fP (\fBlocation\fP &loc)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename Head , typename \&.\&.\&. Tail> static \fBresult\fP< \fBregion\fP, \fBnone_t\fP > \fBtoml::detail::either\fP< Head, Tail\&.\&.\&. >::invoke (\fBlocation\fP & loc)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
