.TH "toml::detail::type_to_enum< T, Value >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::type_to_enum< T, Value >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.PP
Inherits std::conditional::type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
