.TH "toml::detail::type_to_enum< local_datetime, Value >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::type_to_enum< local_datetime, Value >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.PP
Inherits value_t_constant< value_t::local_datetime >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
