.TH "toml::detail::index_sequence_maker< N >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::index_sequence_maker< N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBpush_back_index_sequence\fP< typenameindex_sequence_maker< N\-1 >::type, N >::type \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<std::size_t N> typedef \fBpush_back_index_sequence\fP<typenameindex_sequence_maker<N\-1>::type,N>::type \fBtoml::detail::index_sequence_maker\fP< N >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
