.TH "toml::detail::is_map< T >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::is_map< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits \fBtoml::detail::conjunction< has_iterator< T >, has_value_type< T >, has_key_type< T >, has_mapped_type< T > >\fP\&.
.PP
Inherited by \fBtoml::detail::is_map< T & >\fP, \fBtoml::detail::is_map< T const & >\fP, \fBtoml::detail::is_map< T const volatile & >\fP, and \fBtoml::detail::is_map< T volatile & >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
