.TH "toml::detail::is_basic_value<::toml::basic_value< C, M, V > >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::is_basic_value<::toml::basic_value< C, M, V > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.PP
Inherits std::true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
