.TH "toml::detail::is_exact_toml_type< T const volatile &, V >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::is_exact_toml_type< T const volatile &, V >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.PP
Inherits \fBtoml::detail::is_exact_toml_type< T, V >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
