.TH "toml::detail::in_range< Low, Up >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::in_range< Low, Up >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <combinator\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBresult\fP< \fBregion\fP, \fBnone_t\fP > \fBinvoke\fP (\fBlocation\fP &loc)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr char \fBupper\fP = Up"
.br
.ti -1c
.RI "static constexpr char \fBlower\fP = Low"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<char Low, char Up> static \fBresult\fP< \fBregion\fP, \fBnone_t\fP > \fBtoml::detail::in_range\fP< Low, Up >::invoke (\fBlocation\fP & loc)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<char L, char U> constexpr char \fBtoml::detail::in_range\fP< L, U >::lower = Low\fC [static]\fP, \fC [constexpr]\fP"

.SS "template<char L, char U> constexpr char \fBtoml::detail::in_range\fP< L, U >::upper = Up\fC [static]\fP, \fC [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
