.TH "toml::literals::toml_literals" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::literals::toml_literals
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "inline \fB::toml::basic_value\fP< \fBTOML11_DEFAULT_COMMENT_STRATEGY\fP, std::unordered_map, std::vector > \fBliteral_internal_impl\fP (\fB::toml::detail::location\fP loc)"
.br
.ti -1c
.RI "inline \fB::toml::basic_value\fP< \fBTOML11_DEFAULT_COMMENT_STRATEGY\fP, std::unordered_map, std::vector > \fBoperator''_toml\fP (const char *str, std::size_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "inline \fB::toml::basic_value\fP< \fBTOML11_DEFAULT_COMMENT_STRATEGY\fP, std::unordered_map, std::vector > toml::literals::toml_literals::literal_internal_impl (\fB::toml::detail::location\fP loc)"

.SS "inline \fB::toml::basic_value\fP< \fBTOML11_DEFAULT_COMMENT_STRATEGY\fP, std::unordered_map, std::vector > toml::literals::toml_literals::operator''_toml (const char * str, std::size_t len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
