.TH "toml::detail::push_back_index_sequence< index_sequence< Ns... >, N >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::push_back_index_sequence< index_sequence< Ns... >, N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traits\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBindex_sequence\fP< Ns\&.\&.\&., N > \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<std::size_t N, std::size_t \&.\&.\&. Ns> typedef \fBindex_sequence\fP<Ns\&.\&.\&., N> \fBtoml::detail::push_back_index_sequence\fP< \fBindex_sequence\fP< Ns\&.\&.\&. >, N >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
