.TH "toml::color_ansi::detail" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::color_ansi::detail
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcolorize_index\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int toml::color_ansi::detail::colorize_index ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
