.TH "toml::detail::enum_to_type< value_t::string, Value >" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toml::detail::enum_to_type< value_t::string, Value >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBstring\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename Value > using \fBtoml::detail::enum_to_type\fP< \fBvalue_t::string\fP, Value >::type =  \fBstring\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
