.TH "external/toml/version.hpp" 3 "Sat Jun 18 2022" "Version 1.0" "SuperCold" \" -*- nroff -*-
.ad l
.nh
.SH NAME
external/toml/version.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOML11_CPLUSPLUS_STANDARD_VERSION\fP   __cplusplus"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TOML11_CPLUSPLUS_STANDARD_VERSION   __cplusplus"

.SH "Author"
.PP 
Generated automatically by Doxygen for SuperCold from the source code\&.
