var annotated_dup =
[
    [ "toml", "namespacetoml.html", [
      [ "detail", "namespacetoml_1_1detail.html", [
        [ "at_least", "structtoml_1_1detail_1_1at__least.html", null ],
        [ "character", "structtoml_1_1detail_1_1character.html", null ],
        [ "conjunction", "structtoml_1_1detail_1_1conjunction.html", null ],
        [ "conjunction< T >", "structtoml_1_1detail_1_1conjunction_3_01_t_01_4.html", null ],
        [ "conjunction< T, Ts... >", "structtoml_1_1detail_1_1conjunction_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
        [ "disjunction", "structtoml_1_1detail_1_1disjunction.html", null ],
        [ "disjunction< T >", "structtoml_1_1detail_1_1disjunction_3_01_t_01_4.html", null ],
        [ "disjunction< T, Ts... >", "structtoml_1_1detail_1_1disjunction_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
        [ "either", "structtoml_1_1detail_1_1either.html", null ],
        [ "either< Head >", "structtoml_1_1detail_1_1either_3_01_head_01_4.html", null ],
        [ "either< Head, Tail... >", "structtoml_1_1detail_1_1either_3_01_head_00_01_tail_8_8_8_01_4.html", null ],
        [ "empty_iterator", "structtoml_1_1detail_1_1empty__iterator.html", "structtoml_1_1detail_1_1empty__iterator" ],
        [ "enum_to_type", "structtoml_1_1detail_1_1enum__to__type.html", "structtoml_1_1detail_1_1enum__to__type" ],
        [ "enum_to_type< value_t::array, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1array_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1array_00_01_value_01_4" ],
        [ "enum_to_type< value_t::boolean, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1boolean_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1boolean_00_01_value_01_4" ],
        [ "enum_to_type< value_t::empty, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1empty_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1empty_00_01_value_01_4" ],
        [ "enum_to_type< value_t::floating, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1floating_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1floating_00_01_value_01_4" ],
        [ "enum_to_type< value_t::integer, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1integer_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1integer_00_01_value_01_4" ],
        [ "enum_to_type< value_t::local_date, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1local__date_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1local__date_00_01_value_01_4" ],
        [ "enum_to_type< value_t::local_datetime, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1local__datetime_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1local__datetime_00_01_value_01_4" ],
        [ "enum_to_type< value_t::local_time, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1local__time_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1local__time_00_01_value_01_4" ],
        [ "enum_to_type< value_t::offset_datetime, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1offset__datetime_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1offset__datetime_00_01_value_01_4" ],
        [ "enum_to_type< value_t::string, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1string_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1string_00_01_value_01_4" ],
        [ "enum_to_type< value_t::table, Value >", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1table_00_01_value_01_4.html", "structtoml_1_1detail_1_1enum__to__type_3_01value__t_1_1table_00_01_value_01_4" ],
        [ "exactly", "structtoml_1_1detail_1_1exactly.html", null ],
        [ "exclude", "structtoml_1_1detail_1_1exclude.html", null ],
        [ "has_from_toml_method", "structtoml_1_1detail_1_1has__from__toml__method.html", null ],
        [ "has_from_toml_method_impl", "structtoml_1_1detail_1_1has__from__toml__method__impl.html", null ],
        [ "has_into_toml_method", "structtoml_1_1detail_1_1has__into__toml__method.html", null ],
        [ "has_into_toml_method_impl", "structtoml_1_1detail_1_1has__into__toml__method__impl.html", null ],
        [ "has_iterator", "structtoml_1_1detail_1_1has__iterator.html", null ],
        [ "has_iterator_impl", "structtoml_1_1detail_1_1has__iterator__impl.html", null ],
        [ "has_key_type", "structtoml_1_1detail_1_1has__key__type.html", null ],
        [ "has_key_type_impl", "structtoml_1_1detail_1_1has__key__type__impl.html", null ],
        [ "has_mapped_type", "structtoml_1_1detail_1_1has__mapped__type.html", null ],
        [ "has_mapped_type_impl", "structtoml_1_1detail_1_1has__mapped__type__impl.html", null ],
        [ "has_push_back_method", "structtoml_1_1detail_1_1has__push__back__method.html", null ],
        [ "has_push_back_method_impl", "structtoml_1_1detail_1_1has__push__back__method__impl.html", null ],
        [ "has_reserve_method", "structtoml_1_1detail_1_1has__reserve__method.html", null ],
        [ "has_reserve_method_impl", "structtoml_1_1detail_1_1has__reserve__method__impl.html", null ],
        [ "has_specialized_from", "structtoml_1_1detail_1_1has__specialized__from.html", null ],
        [ "has_specialized_from_impl", "structtoml_1_1detail_1_1has__specialized__from__impl.html", null ],
        [ "has_specialized_into", "structtoml_1_1detail_1_1has__specialized__into.html", null ],
        [ "has_specialized_into_impl", "structtoml_1_1detail_1_1has__specialized__into__impl.html", null ],
        [ "has_value_type", "structtoml_1_1detail_1_1has__value__type.html", null ],
        [ "has_value_type_impl", "structtoml_1_1detail_1_1has__value__type__impl.html", null ],
        [ "in_range", "structtoml_1_1detail_1_1in__range.html", null ],
        [ "index_sequence", "structtoml_1_1detail_1_1index__sequence.html", null ],
        [ "index_sequence_maker", "structtoml_1_1detail_1_1index__sequence__maker.html", "structtoml_1_1detail_1_1index__sequence__maker" ],
        [ "index_sequence_maker< 0 >", "structtoml_1_1detail_1_1index__sequence__maker_3_010_01_4.html", "structtoml_1_1detail_1_1index__sequence__maker_3_010_01_4" ],
        [ "is_basic_value", "structtoml_1_1detail_1_1is__basic__value.html", null ],
        [ "is_basic_value< T & >", "structtoml_1_1detail_1_1is__basic__value_3_01_t_01_6_01_4.html", null ],
        [ "is_basic_value< T const & >", "structtoml_1_1detail_1_1is__basic__value_3_01_t_01const_01_6_01_4.html", null ],
        [ "is_basic_value< T const volatile & >", "structtoml_1_1detail_1_1is__basic__value_3_01_t_01const_01volatile_01_6_01_4.html", null ],
        [ "is_basic_value< T volatile & >", "structtoml_1_1detail_1_1is__basic__value_3_01_t_01volatile_01_6_01_4.html", null ],
        [ "is_basic_value<::toml::basic_value< C, M, V > >", "structtoml_1_1detail_1_1is__basic__value_3_1_1toml_1_1basic__value_3_01_c_00_01_m_00_01_v_01_4_01_4.html", null ],
        [ "is_chrono_duration", "structtoml_1_1detail_1_1is__chrono__duration.html", null ],
        [ "is_chrono_duration< std::chrono::duration< Rep, Period > >", "structtoml_1_1detail_1_1is__chrono__duration_3_01std_1_1chrono_1_1duration_3_01_rep_00_01_period_01_4_01_4.html", null ],
        [ "is_comparable", "structtoml_1_1detail_1_1is__comparable.html", null ],
        [ "is_comparable_impl", "structtoml_1_1detail_1_1is__comparable__impl.html", null ],
        [ "is_container", "structtoml_1_1detail_1_1is__container.html", null ],
        [ "is_container< T & >", "structtoml_1_1detail_1_1is__container_3_01_t_01_6_01_4.html", null ],
        [ "is_container< T const & >", "structtoml_1_1detail_1_1is__container_3_01_t_01const_01_6_01_4.html", null ],
        [ "is_container< T const volatile & >", "structtoml_1_1detail_1_1is__container_3_01_t_01const_01volatile_01_6_01_4.html", null ],
        [ "is_container< T volatile & >", "structtoml_1_1detail_1_1is__container_3_01_t_01volatile_01_6_01_4.html", null ],
        [ "is_exact_toml_type", "structtoml_1_1detail_1_1is__exact__toml__type.html", null ],
        [ "is_exact_toml_type< T &, V >", "structtoml_1_1detail_1_1is__exact__toml__type_3_01_t_01_6_00_01_v_01_4.html", null ],
        [ "is_exact_toml_type< T const &, V >", "structtoml_1_1detail_1_1is__exact__toml__type_3_01_t_01const_01_6_00_01_v_01_4.html", null ],
        [ "is_exact_toml_type< T const volatile &, V >", "structtoml_1_1detail_1_1is__exact__toml__type_3_01_t_01const_01volatile_01_6_00_01_v_01_4.html", null ],
        [ "is_exact_toml_type< T volatile &, V >", "structtoml_1_1detail_1_1is__exact__toml__type_3_01_t_01volatile_01_6_00_01_v_01_4.html", null ],
        [ "is_map", "structtoml_1_1detail_1_1is__map.html", null ],
        [ "is_map< T & >", "structtoml_1_1detail_1_1is__map_3_01_t_01_6_01_4.html", null ],
        [ "is_map< T const & >", "structtoml_1_1detail_1_1is__map_3_01_t_01const_01_6_01_4.html", null ],
        [ "is_map< T const volatile & >", "structtoml_1_1detail_1_1is__map_3_01_t_01const_01volatile_01_6_01_4.html", null ],
        [ "is_map< T volatile & >", "structtoml_1_1detail_1_1is__map_3_01_t_01volatile_01_6_01_4.html", null ],
        [ "is_std_forward_list", "structtoml_1_1detail_1_1is__std__forward__list.html", null ],
        [ "is_std_forward_list< std::forward_list< T > >", "structtoml_1_1detail_1_1is__std__forward__list_3_01std_1_1forward__list_3_01_t_01_4_01_4.html", null ],
        [ "is_std_pair", "structtoml_1_1detail_1_1is__std__pair.html", null ],
        [ "is_std_pair< std::pair< T1, T2 > >", "structtoml_1_1detail_1_1is__std__pair_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_std_tuple", "structtoml_1_1detail_1_1is__std__tuple.html", null ],
        [ "is_std_tuple< std::tuple< Ts... > >", "structtoml_1_1detail_1_1is__std__tuple_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_string_literal", "structtoml_1_1detail_1_1is__string__literal.html", null ],
        [ "last_one_in_pack", "structtoml_1_1detail_1_1last__one__in__pack.html", "structtoml_1_1detail_1_1last__one__in__pack" ],
        [ "last_one_in_pack< T >", "structtoml_1_1detail_1_1last__one__in__pack_3_01_t_01_4.html", "structtoml_1_1detail_1_1last__one__in__pack_3_01_t_01_4" ],
        [ "location", "structtoml_1_1detail_1_1location.html", "structtoml_1_1detail_1_1location" ],
        [ "maybe", "structtoml_1_1detail_1_1maybe.html", null ],
        [ "negation", "structtoml_1_1detail_1_1negation.html", null ],
        [ "none_t", "structtoml_1_1detail_1_1none__t.html", null ],
        [ "push_back_index_sequence", "structtoml_1_1detail_1_1push__back__index__sequence.html", null ],
        [ "push_back_index_sequence< index_sequence< Ns... >, N >", "structtoml_1_1detail_1_1push__back__index__sequence_3_01index__sequence_3_01_ns_8_8_8_01_4_00_01_n_01_4.html", "structtoml_1_1detail_1_1push__back__index__sequence_3_01index__sequence_3_01_ns_8_8_8_01_4_00_01_n_01_4" ],
        [ "region", "structtoml_1_1detail_1_1region.html", "structtoml_1_1detail_1_1region" ],
        [ "region_base", "structtoml_1_1detail_1_1region__base.html", "structtoml_1_1detail_1_1region__base" ],
        [ "remove_cvref", "structtoml_1_1detail_1_1remove__cvref.html", "structtoml_1_1detail_1_1remove__cvref" ],
        [ "repeat", "structtoml_1_1detail_1_1repeat.html", null ],
        [ "repeat< T, at_least< N > >", "structtoml_1_1detail_1_1repeat_3_01_t_00_01at__least_3_01_n_01_4_01_4.html", null ],
        [ "repeat< T, exactly< N > >", "structtoml_1_1detail_1_1repeat_3_01_t_00_01exactly_3_01_n_01_4_01_4.html", null ],
        [ "repeat< T, unlimited >", "structtoml_1_1detail_1_1repeat_3_01_t_00_01unlimited_01_4.html", null ],
        [ "sequence", "structtoml_1_1detail_1_1sequence.html", null ],
        [ "sequence< Head >", "structtoml_1_1detail_1_1sequence_3_01_head_01_4.html", null ],
        [ "sequence< Head, Tail... >", "structtoml_1_1detail_1_1sequence_3_01_head_00_01_tail_8_8_8_01_4.html", null ],
        [ "storage", "structtoml_1_1detail_1_1storage.html", "structtoml_1_1detail_1_1storage" ],
        [ "switch_cast", "structtoml_1_1detail_1_1switch__cast.html", null ],
        [ "type_to_enum", "structtoml_1_1detail_1_1type__to__enum.html", null ],
        [ "type_to_enum< boolean, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01boolean_00_01_value_01_4.html", null ],
        [ "type_to_enum< floating, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01floating_00_01_value_01_4.html", null ],
        [ "type_to_enum< integer, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01integer_00_01_value_01_4.html", null ],
        [ "type_to_enum< local_date, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01local__date_00_01_value_01_4.html", null ],
        [ "type_to_enum< local_datetime, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01local__datetime_00_01_value_01_4.html", null ],
        [ "type_to_enum< local_time, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01local__time_00_01_value_01_4.html", null ],
        [ "type_to_enum< offset_datetime, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01offset__datetime_00_01_value_01_4.html", null ],
        [ "type_to_enum< string, Value >", "structtoml_1_1detail_1_1type__to__enum_3_01string_00_01_value_01_4.html", null ],
        [ "unlimited", "structtoml_1_1detail_1_1unlimited.html", null ]
      ] ],
      [ "basic_value", "classtoml_1_1basic__value.html", "classtoml_1_1basic__value" ],
      [ "discard_comments", "structtoml_1_1discard__comments.html", "structtoml_1_1discard__comments" ],
      [ "exception", "structtoml_1_1exception.html", "structtoml_1_1exception" ],
      [ "failure", "structtoml_1_1failure.html", "structtoml_1_1failure" ],
      [ "from", "structtoml_1_1from.html", null ],
      [ "internal_error", "structtoml_1_1internal__error.html", "structtoml_1_1internal__error" ],
      [ "into", "structtoml_1_1into.html", null ],
      [ "local_date", "structtoml_1_1local__date.html", "structtoml_1_1local__date" ],
      [ "local_datetime", "structtoml_1_1local__datetime.html", "structtoml_1_1local__datetime" ],
      [ "local_time", "structtoml_1_1local__time.html", "structtoml_1_1local__time" ],
      [ "offset_datetime", "structtoml_1_1offset__datetime.html", "structtoml_1_1offset__datetime" ],
      [ "preserve_comments", "structtoml_1_1preserve__comments.html", "structtoml_1_1preserve__comments" ],
      [ "result", "structtoml_1_1result.html", "structtoml_1_1result" ],
      [ "serializer", "structtoml_1_1serializer.html", "structtoml_1_1serializer" ],
      [ "source_location", "structtoml_1_1source__location.html", "structtoml_1_1source__location" ],
      [ "string", "structtoml_1_1string.html", "structtoml_1_1string" ],
      [ "success", "structtoml_1_1success.html", "structtoml_1_1success" ],
      [ "syntax_error", "structtoml_1_1syntax__error.html", "structtoml_1_1syntax__error" ],
      [ "time_offset", "structtoml_1_1time__offset.html", "structtoml_1_1time__offset" ],
      [ "type_error", "structtoml_1_1type__error.html", "structtoml_1_1type__error" ]
    ] ],
    [ "Bullet", "class_bullet.html", "class_bullet" ],
    [ "EyeEnemy", "class_eye_enemy.html", "class_eye_enemy" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PriorityQueue", "class_priority_queue.html", "class_priority_queue" ],
    [ "SettingsManager", "struct_settings_manager.html", "struct_settings_manager" ],
    [ "SimplexNoise", "class_simplex_noise.html", "class_simplex_noise" ],
    [ "SpriteController", "struct_sprite_controller.html", "struct_sprite_controller" ],
    [ "TileMap", "class_tile_map.html", "class_tile_map" ]
];